### ISSUE TITLE
Polyfill Function.bind

### ISSUE THREAD

**Issue by bdowning** [bdowning/shifty-core#5]
Amazingly PhantomJS doesn't have this.  Polyfill it so that the Rekapi test suite can run properly.

**Comment by jeremyckahn** [comment]
It looks like this was fixed for [PhantomJS 2.0](https://github.com/ariya/phantomjs/issues/10522#issuecomment-72705658).

**Comment by bdowning** [comment]
I saw that comment too, but both my system and the Rekapi node_modules version of PhantomJS is 2.1.1 and it still fails.

```
%% 11766 firnen:~/projects/mrm/timecode                               
:; phantomjs --version                                     
2.1.1
%% 11767 firnen:~/projects/mrm/timecode                               
:; ../rekapi/node_modules/phantomjs/bin/phantomjs --version
2.1.1
```
